---
- hosts: droplets_iTrust
  gather_facts: no
  remote_user: root
  
  vars:
    git_repo_folder: /root/iTrust2-v2

  tasks:  
  
  - name: Add dependenies 
    roles:
    - refresh-apt
    - java8
    - maven
    - git
   
  - name: delete directory if it exists
    file:
      path: "{{ git_repo_folder }}"
      state: absent

  - name: Clone iTrust repository
    git:
      repo: https://github.com/qiufengyu21/iTrustv2-v2
      dest: "{{ git_repo_folder }}"
      clone: yes
      force: yes

  - name: Rename the db.properties.template file 
    copy: 
      remote_src: yes
      src: "{{ git_repo_folder }}/iTrust2/src/main/java/db.properties.template"
      dest: "{{ git_repo_folder }}/iTrust2/src/main/java/db.properties"

  - name: edit db.properties file to connect mysql_server
    replace:
      path: "{{ git_repo_folder }}/iTrust2/src/main/java/db.properties"
      regexp: localhost
      replace: "{{lookup('file', 'mysql.info') }}"

  - name: Rename the hibernate.properties.template file 
    copy: 
      remote_src: yes
      src: "{{ git_repo_folder }}/iTrust2/src/main/resources/hibernate.properties.template"
      dest: "{{ git_repo_folder }}/iTrust2/src/main/resources/hibernate.properties"
  
  - name: edit hibernate.properties file to connect mysql_server
    replace:
      path: "{{ git_repo_folder }}/iTrust2/src/main/resources/hibernate.properties"
      regexp: localhost
      replace: "{{lookup('file', 'mysql.info') }}"

  - name: Rename the email.properties.template file
    copy: 
      remote_src: yes
      src: "{{ git_repo_folder }}/iTrust2/src/main/java/email.properties.template"
      dest: "{{ git_repo_folder }}/iTrust2/src/main/java/email.properties"
   
  - name: Download Tomcat and extract
    unarchive:
      remote_src: yes
      src: http://mirror.cc.columbia.edu/pub/software/apache/tomcat/tomcat-9/v9.0.7/bin/apache-tomcat-9.0.7.tar.gz
      dest: "{{ git_repo_folder }}/"

  - name: Build the database and create sample data
    shell: mvn process-test-classes
    args:
      chdir: "{{ git_repo_folder }}/iTrust2"

  - name: Run iTrust
    shell: nohup bash -c "mvn jetty:run" &
    args:
      chdir: "{{ git_repo_folder }}/iTrust2"

  - name: Wait 300 seconds for port 8080 to become open on the host, don't start checking for 15 seconds
    wait_for:
      port: 8080
      delay: 15

#- import_playbook: update.yml