---
- hosts: droplets_mysql
  remote_user: root
  gather_facts: no
 
  roles:
    - refresh-apt
    - python-pip
    - mysql-server
    - mysql-python

  tasks:  
    
  - name: Comment out bind-address
    replace:
      path: /etc/mysql/my.cnf
      regexp: bind-address
      replace: "# bind-address"

  - name: Edit my.cnf file - add required lines
    blockinfile:
      path: /etc/mysql/my.cnf
      block: |
        [mysql]
        skip-grant-tables

  - name: Set mysql user privileges
    mysql_user:
      name: root
      host: "%"
      priv: "*.*:ALL"
      state: present

  - name: Restart mysql
    service:
      name: mysql
      state: restarted