---
- hosts: droplets_mysql
  remote_user: root
  gather_facts: no
 
  tasks:  
  
  - name: Add dependenies 
    roles:
    - refresh-apt
    - python-pip
    - mysql-server
    - mysql-python
    
  - name: edit my.cnf file - remove extra line
    lineinfile:
      path: /etc/mysql/my.cnf
      line: [mysql]
      state: absent

  - name: comment out bind-address
    replace:
      path: /etc/mysql/my.cnf
      regexp: bind-address
      replace: "# bind-address"

  - name: edit my.cnf file - add required lines
    blockinfile:
      path: /etc/mysql/my.cnf
      block: |
        [mysql]
        skip-grant-tables

  - name: Set mysql user privileges
    mysql_user:
      name: root
      host: "%"
      priv: "*.*:ALL"
      state: present

  - name: restart mysql
    service:
      name: mysql
      state: restarted