---
- hosts: localhost

  vars:
    do_token: "{{ lookup('env', 'DOTOKEN') }}"
    git_username: "{{ lookup('env', 'GITUSER') }}"
    git_auth: "{{ lookup('env', 'GITAUTH') }}"
    droplets_iTrust:
    - droplet-iTrust-1
    - droplet-iTrust-2
    # - droplet-iTrust-3
    # - droplet-iTrust-4
    # - droplet-iTrust-5
    
  tasks:
  - name: install pip
    become: yes
    apt:
      name: python-pip
  
  - name: install dopy
    become: yes
    pip:
      name: dopy
      version: 0.3.5

  - name: ensure ssh key exists
    user:
      name: "{{ ansible_user_id }}"
      generate_ssh_key: yes
      ssh_key_file: .ssh/id_rsa
  
  - name: ensure key exists at DigitalOcean
    digital_ocean:
      state: present
      command: ssh
      name: my_ssh_key
      ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      api_token: "{{ do_token }}"
    register: my_ssh_key

 # Create droplet for mysql
  - name: create droplet for mysql server if it does not exists
    digital_ocean:
      state: present
      command: droplet
      name: droplet-mysql
      unique_name: yes
      size_id: 1gb
      region_id: sgp1
      image_id: ubuntu-14-04-x64
      ssh_key_ids: "{{ my_ssh_key.ssh_key.id }}"
      api_token: "{{ do_token }}"
    register: droplet_mysql_details
  
  - name: display IP
    debug:
      msg: "IP is {{ droplet_mysql_details.droplet.ip_address }}"
  
  - name: add new host to inventory 
    add_host:
      name: "{{ droplet_mysql_details.droplet.ip_address }}"
      group: droplets_mysql
  
  - name: Wait 300 seconds for port 22 to become open on the droplet, don't start checking for 5 seconds
    wait_for:
      host: "{{ droplet_mysql_details.droplet.ip_address }}"
      port: 22
      delay: 5

  # create droplets for iTrust
  - name: create droplets for iTrust if it does not exists
    digital_ocean:
      state: present
      command: droplet
      name: "{{ item }}"
      unique_name: yes
      size_id: 1gb
      region_id: sgp1
      image_id: ubuntu-14-04-x64
      ssh_key_ids: "{{ my_ssh_key.ssh_key.id }}"
      api_token: "{{ do_token }}"
      wait_timeout: 180
    with_items: "{{ droplets_iTrust }}"  
    register: droplets_iTrust_details
  
  - name: display IP address of droplet created
    debug: 
      msg:"IP is {{ item.droplet.ip_address }}"
    with_items: "{{ droplets_iTrust_details.results }}"
  
  - name: add new host to inventory 
    add_host:
      name: "{{ item.droplet.ip_address }}"
      group: droplets_iTrust
    with_items: "{{ droplets_iTrust_details.results }}"
  
  - name: Wait 300 seconds for port 22 to become open on the droplet, don't start checking for 10 seconds
    wait_for:
      host: "{{ item.droplet.ip_address }}"
      port: 22
      delay: 10
    with_items: "{{ droplets_iTrust_details.results }}"

  - name: Write mysql IP to a file
    copy:
      content: "{{ droplet_mysql_details.droplet.ip_address }}"
      dest: mysql.info

- import_playbook: mysql-setup.yml
- import_playbook: itrust-setup.yml
