- hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    mongo_user: admin
    mongo_password: admin123
    git_repo_folder: "/home/vagrant/checkbox.io"

  environment:
    MONGO_PORT: 3002
    MONGO_IP: 127.0.0.1
    MONGO_USER: "{{ mongo_user }}"
    MONGO_PASSWORD: "{{ mongo_password }}"

  tasks:
  - name: add key for mongodb
    become: yes
    become_method: sudo
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 7F0CEB10
      state: present

  - name: add mongodb repo
    become: yes
    become_method: sudo
    lineinfile:
      line: "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse"
      dest: /etc/apt/sources.list.d/mongodb-org-3.0.list
      state: present
      create: yes

  - name: add key nodejs
    become: yes
    become_method: sudo
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 68576280
      state: present

  - name: add nodejs repo
    become: yes
    become_method: sudo
    apt_repository:
      repo: 'deb https://deb.nodesource.com/node_7.x {{ ansible_distribution_release }} main'

  - name: apt-get update
    become: yes
    become_method: sudo
    apt:
      update_cache: true

  - name: install mongodb, nodejs, npm, nginx and pip3
    become: yes
    become_method: sudo
    apt: pkg={{ item }} state=installed update_cache=true cache_valid_time=3600
    with_items: 
    - mongodb-org
    - nodejs
    - npm
    - nginx
    - python-pip
