---
- hosts: localhost
  connection: local
  vars:
    - do_token: "{{ lookup('env', 'DOTOKEN') }}"
  roles:
    - prereqs
    - provision-vms

- hosts: mongodb_host
  remote_user: root
  vars_prompt:
    - name: "mongo_user"
      prompt: "enter mongo admin user"
    - name: "mongo_password"
      prompt: "enter mongodb password"
  roles:
    - mongodb

- hosts: droplets
  remote_user: root
  vars:
    git_repo_folder: "/home/vagrant/checkbox.io"
    mip: "{{ hostvars['localhost']['droplet_mongodb']['droplet']['ip_address'] }}"
    mu: "{{ hostvars[groups['mongodb_host'][0]]['mongo_user'] }}"
    mp: "{{ hostvars[groups['mongodb_host'][0]]['mongo_password'] }}"
  environment:
    MONGO_PORT: 3002
    MONGO_IP: "{{ mip }}"
    MONGO_USER: "{{ mu }}"
    MONGO_PASSWORD: "{{ mp }}"
  roles:
    - checkboxio
