---
- hosts: localhost
  connection: local

  vars:
    repoUrl: https://github.com/patel-bhavik/iTrust2-v2.git
    destPath: /home/vagrant/deployment/iTrust2-v2
    
  tasks:
  - name: clone iTrust repo
    git:
      repo: "{{ repoUrl }}"
      dest: "{{ destPath }}"
      force: yes
      
  - name: Copy Post Commit Hook
    template:
      force: yes
      src: "/home/vagrant/deployment/templates/post-commit"
      dest: "{{ destPath }}/.git/hooks"
      mode: 0755
    become: yes