- name: copy load balancer code
  become: yes
  copy:
    src: lb.py
    dest: "{{ lb_folder }}/"

- name: see VM ips
  debug:
    msg: "prod: {{ prod_ip }} staging: {{ staging_ip }}"

- name: run load balancer
  become: yes
  shell: nohup bash -c "python lb.py {{ prod_ip }} {{ staging_ip }}" &
  register: lb_output
  args:
    chdir: "{{ lb_folder }}"

- name: see lb run output
  debug:
    msg: "{{ lb_output }}"
