- name: copy load balancer code
  become: yes
  copy:
    src: lb.py
    dest: "{{ ansible_env.HOME }}/"

- name: run load balancer
  become: yes
  shell: nohup bash -c "python lb.py {{ prod_ip }} {{ staging_ip }}" &
  register: lb_output
  args:
    chdir: "{{ ansible_env.HOME }}"

