---
- import_playbook: provisioning-vm-iTrust.yml

- hosts: new_droplet
  gather_facts: no
  remote_user: root
  vars:
    git_repo_folder: /root/iTrust2-v2

  tasks:
  - import_tasks: mysql-setup.yml
  - import_tasks: itrust-setup.yml
