---
- hosts: localhost
  connection: local

  vars:
    do_token: "{{ lookup('env', 'DOTOKEN') }}"
  
  tasks:
  
  - name: ensure ssh key exists
    user:
      name: "{{ ansible_user_id }}"
      generate_ssh_key: yes
      ssh_key_file: .ssh/id_rsa
  
  - name: ensure key exists at DigitalOcean
    digital_ocean:
      state: present
      command: ssh
      name: my_ssh_key
      ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      api_token: "{{ do_token }}"
    register: my_ssh_key
  
  - name: create droplet if it does not exists
    digital_ocean:
      state: present
      command: droplet
      name: droplet-one
      unique_name: no
      size_id: 1gb
      region_id: sgp1
      image_id: ubuntu-16-04-x64
      ssh_key_ids: "{{ my_ssh_key.ssh_key.id }}"
      api_token: "{{ do_token }}"
      wait_timeout: 180
    register: droplet_one
  
  - name: display IP address of droplet created
    debug: 
      msg: "IP is {{ droplet_one.droplet.ip_address }}"
  
  - name: add new host to inventory 
    add_host:
      name: "{{ droplet_one.droplet.ip_address }}"
      group: new_droplet
  
  - name: Wait 300 seconds for port 22 to become open on the droplet, don't start checking for 10 seconds
    wait_for:
      host: "{{ droplet_one.droplet.ip_address }}"
      port: 22
      delay: 10
  - name: Write the new droplet key to known hosts
    shell: "/usr/bin/ssh-keyscan -H {{ droplet_one.droplet.ip_address }} >> /var/lib/jenkins/.ssh/known_hosts"
